/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_ReservasiHotel;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Gzt
 */
public class ReservasiHotel extends javax.swing.JFrame {

    /**
     * Creates new form ReservasiHotel
     */
    int harga;

    public ReservasiHotel() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("src/GUI_ReservasiHotel/Logohotel.png");
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomertelp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Jeniskelamin = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Datacustomer = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        Identitas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        Reservasi = new javax.swing.JButton();
        Bersih = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Pajak = new javax.swing.JTextField();
        Jumlah = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Anak = new javax.swing.JSpinner();
        Dewasa = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        Jumlahkamar = new javax.swing.JSpinner();
        Class = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Jlabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DetilKelas = new javax.swing.JTextArea();
        Date1 = new com.toedter.calendar.JDateChooser();
        Date2 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        Jlabel1 = new javax.swing.JLabel();
        Jlabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Jlabel3 = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOTEL MERAH PUTIH");
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(153, 167, 153));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 73, 65));
        jLabel2.setText("DATA");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 73, 65));
        jLabel3.setText("Nama");

        Nama.setBackground(new java.awt.Color(68, 73, 65));
        Nama.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        Nama.setForeground(new java.awt.Color(204, 204, 204));
        Nama.setCaretColor(new java.awt.Color(102, 102, 102));
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 73, 65));
        jLabel4.setText("Alamat");

        Alamat.setBackground(new java.awt.Color(68, 73, 65));
        Alamat.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        Alamat.setForeground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 73, 65));
        jLabel5.setText("No. Telepon");
        jLabel5.setToolTipText("");

        nomertelp.setBackground(new java.awt.Color(68, 73, 65));
        nomertelp.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        nomertelp.setForeground(new java.awt.Color(204, 204, 204));

        jLabel6.setBackground(new java.awt.Color(68, 73, 65));
        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 73, 65));
        jLabel6.setText("Jenis Kelamin");

        Jeniskelamin.setBackground(new java.awt.Color(95, 122, 97));
        Jeniskelamin.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Jeniskelamin.setForeground(new java.awt.Color(204, 204, 204));
        Jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-Laki", "Perempuan" }));
        Jeniskelamin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Datacustomer.setEditable(false);
        Datacustomer.setBackground(new java.awt.Color(113, 129, 119));
        Datacustomer.setColumns(20);
        Datacustomer.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Datacustomer.setRows(5);
        jScrollPane2.setViewportView(Datacustomer);

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 73, 65));
        jLabel10.setText("Kartu identitas");

        Identitas.setBackground(new java.awt.Color(95, 122, 97));
        Identitas.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Identitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "KTP", "Passport", "SIM", "Lainnya" }));
        Identitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(125, 125, 125))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jeniskelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nomertelp)
                            .addComponent(Alamat)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(Identitas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomertelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Identitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel2.setBackground(new java.awt.Color(154, 148, 131));
        jPanel2.setForeground(new java.awt.Color(102, 128, 106));

        Reservasi.setBackground(new java.awt.Color(0, 0, 0));
        Reservasi.setForeground(new java.awt.Color(204, 204, 204));
        Reservasi.setText("Reservasi");
        Reservasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasiActionPerformed(evt);
            }
        });

        Bersih.setBackground(new java.awt.Color(0, 0, 0));
        Bersih.setForeground(new java.awt.Color(204, 204, 204));
        Bersih.setText("Bersih");
        Bersih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(68, 73, 65));
        jLabel13.setText("Jumlah");

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(68, 73, 65));
        jLabel14.setText("Pajak");

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(68, 73, 65));
        jLabel15.setText("Total Bayar");

        Pajak.setEditable(false);
        Pajak.setBackground(new java.awt.Color(83, 74, 59));
        Pajak.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        Pajak.setForeground(new java.awt.Color(204, 204, 204));
        Pajak.setText(" Rp.");

        Jumlah.setEditable(false);
        Jumlah.setBackground(new java.awt.Color(83, 74, 59));
        Jumlah.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        Jumlah.setForeground(new java.awt.Color(204, 204, 204));
        Jumlah.setText(" Rp.");

        Total.setEditable(false);
        Total.setBackground(new java.awt.Color(83, 74, 59));
        Total.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        Total.setForeground(new java.awt.Color(204, 204, 204));
        Total.setText(" Rp.");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 73, 65));
        jLabel9.setText("Anak");

        Anak.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Anak.setModel(new javax.swing.SpinnerNumberModel());
        Anak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Dewasa.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Dewasa.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        Dewasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 73, 65));
        jLabel8.setText("Dewasa");

        Jumlahkamar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Jumlahkamar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        Jumlahkamar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Class.setBackground(new java.awt.Color(68, 73, 65));
        Class.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "(STD) Standar Room", "(DLX) Deluxe Room", "(SUP) Superior Room", "(JSR) Junior Suite Room", "(STE) Suite Room" }));
        Class.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 73, 65));
        jLabel7.setText("Kelas");

        Jlabel.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Jlabel.setForeground(new java.awt.Color(68, 73, 65));
        Jlabel.setText("Jumlah Kamar");
        Jlabel.setToolTipText(" ");

        DetilKelas.setEditable(false);
        DetilKelas.setBackground(new java.awt.Color(100, 89, 75));
        DetilKelas.setColumns(20);
        DetilKelas.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        DetilKelas.setForeground(new java.awt.Color(204, 204, 204));
        DetilKelas.setRows(5);
        DetilKelas.setCaretColor(new java.awt.Color(102, 102, 102));
        DetilKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DetilKelas.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(DetilKelas);

        Date1.setBackground(new java.awt.Color(68, 73, 65));
        Date1.setForeground(new java.awt.Color(134, 84, 57));

        Date2.setBackground(new java.awt.Color(68, 73, 65));
        Date2.setForeground(new java.awt.Color(134, 84, 57));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(68, 73, 65));
        jLabel11.setText("Reservasi");

        Jlabel1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Jlabel1.setForeground(new java.awt.Color(68, 73, 65));
        Jlabel1.setText("Chech In");
        Jlabel1.setToolTipText(" ");

        Jlabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Jlabel2.setForeground(new java.awt.Color(68, 73, 65));
        Jlabel2.setText("Check Out");
        Jlabel2.setToolTipText(" ");

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(68, 73, 65));
        jLabel16.setText("Detail Kamar");

        Jlabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Jlabel3.setForeground(new java.awt.Color(68, 73, 65));
        Jlabel3.setText("Orang : ");
        Jlabel3.setToolTipText(" ");

        Close.setBackground(new java.awt.Color(0, 0, 0));
        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Pajak, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(Jlabel1)
                                        .addComponent(Jlabel2))
                                    .addGap(20, 20, 20))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Class, javax.swing.GroupLayout.Alignment.LEADING, 0, 210, Short.MAX_VALUE)
                                        .addComponent(Date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Date1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Jlabel)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(Jlabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8))))
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Dewasa, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Jumlahkamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(Anak)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jScrollPane3)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Reservasi, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(Bersih, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dewasa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabel1)
                            .addComponent(Jlabel)
                            .addComponent(Jumlahkamar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Jlabel3)
                                .addComponent(jLabel8))
                            .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anak, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Reservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Total))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(100, 89, 75));

        Tabel.setBackground(new java.awt.Color(142, 128, 106));
        Tabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        Tabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Tabel.setForeground(new java.awt.Color(246, 242, 212));
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Alamat", "No. Telp", "Kartu Identitas", "Kelas Kamar", "Orang", "Check In", "Check Out", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabel.setDragEnabled(true);
        Tabel.setGridColor(new java.awt.Color(224, 192, 151));
        Tabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Tabel);

        Delete.setBackground(new java.awt.Color(0, 0, 0));
        Delete.setForeground(new java.awt.Color(204, 204, 204));
        Delete.setText("Hapus");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(142, 128, 106));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(180, 198, 166));
        jLabel1.setText("Reservasi HOTEL MERAH PUTIH");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel tabel = (DefaultTableModel) Tabel.getModel();
        int pilihkolom = Tabel.getSelectedRow();
        tabel.removeRow(pilihkolom);
    }//GEN-LAST:event_DeleteActionPerformed

    private void TabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelAncestorAdded

    private void ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassActionPerformed
        String setkelas = Class.getSelectedItem().toString(), getkelas = null;

        if (null != setkelas) {
            switch (setkelas) {
                case "(STD) Standar Room":
                    getkelas = "> 1 bed (Queen size)\n> Kamar mandi\n> AC\n> Perlengkapan Mandi\n> Handuk\n> Makan 2x/hari (pagi,sore)\n==(Rp.1000.000/hari)==";
                    harga = 1000000;
                    break;
                case "(DLX) Deluxe Room":
                    getkelas = "> 1 bed (Queen size)\n> or 2 bed (Single Size)\n> Kamar mandi\n> AC\n> Perlengkapan Mandi"
                            + "\n> HanduknMakan 2x/hari (pagi,sore)\n==(Rp.1500.000/hari)==";
                    harga = 1500000;
                    break;
                case "(SUP) Superior Room":
                    getkelas = "> 1 bed (King size)\n> Kamar mandi\n> AC\n> Perlengkapan Mandi\n> Handuk\n> Pemandangan Luar"
                            + "\n> Makan 2x/hari (pagi,sore)\n==(Rp.2000.000/hari)==";
                    harga = 2000000;
                    break;
                case "(JSR) Junior Suite Room":
                    getkelas = "> 2 bed (1 king size & 1 Queen size)\n> Kamar mandi\n> AC\n> Perlengkapan Mandi\n> Handuk\n> Ruang Tamu"
                            + "\n> Makan 2x/hari (pagi,sore)\n==(Rp.3000.000/hari)==";
                    harga = 3000000;
                    break;
                case "(STE) Suite Room":
                    getkelas = "> 3 bed (1 King size & 2 Queen size)\n> Kamar mandi\n> AC\n> Perlengkapan Mandi"
                            + "\n> Handuk\n> Ruang Tamu\n> Dapur\n> Kulkas\n> Makan 2x/hari (pagi,sore)\n==(Rp.5000.000/hari)==";
                    harga = 5000000;
                    break;
                default:
                    break;
            }
        }
        DetilKelas.setText(getkelas);
    }//GEN-LAST:event_ClassActionPerformed

    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
        Nama.setText(null);
        Alamat.setText(null);
        nomertelp.setText(null);
        Dewasa.setValue(1);
        Anak.setValue(0);
        Jumlahkamar.setValue(1);
        DetilKelas.setText(null);
        Jeniskelamin.setSelectedItem("Pilih");
        Datacustomer.setText(null);
        Jumlah.setText(null);
        Pajak.setText(null);
        Total.setText(null);
        Class.setSelectedItem("Pilih");
        Identitas.setSelectedItem("Pilih");
        Date1.setCalendar(null);
        Date2.setCalendar(null);
    }//GEN-LAST:event_BersihActionPerformed

    private void ReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasiActionPerformed

        try {
            DefaultTableModel tabel = (DefaultTableModel) Tabel.getModel();
            SimpleDateFormat tanggal = new SimpleDateFormat("yyyy-MM-dd");

            if ((Nama.getText().equals("") || nomertelp.getText().equals("") || Alamat.getText().equals("")
                    || Class.getSelectedItem().equals("Pilih") || Jeniskelamin.getSelectedItem().equals("Pilih")
                    || Identitas.getSelectedItem().equals("Pilih")) == true) {
                JOptionPane.showMessageDialog(null, "Terdapat data yang belum lengkap\nCek dan Lengkapi!!!");
                return;
            }

            String tgl1 = String.valueOf(tanggal.format(Date1.getDate()));
            Date masuk = (Date) tanggal.parse(tgl1);

            String tgl2 = String.valueOf(tanggal.format(Date2.getDate()));
            Date keluar = (Date) tanggal.parse(tgl2);
            long jumlahhari = Math.abs(keluar.getTime() - masuk.getTime());
            int hari = (int) TimeUnit.MILLISECONDS.toDays(jumlahhari);

            String jumlah = Integer.toString(harga * (int) Jumlahkamar.getValue() * hari);
            String PajakH = Integer.toString((int) ((harga * (int) Jumlahkamar.getValue() * hari) * 0.1));
            String TotalH = Integer.toString((int) ((harga * (int) Jumlahkamar.getValue() * hari) * 0.1) + (harga * (int) Jumlahkamar.getValue() * hari));
            Jumlah.setText(" Rp. " + jumlah); //menampilkan jumlah harga
            Pajak.setText(" Rp. " + PajakH); //menampilkan pajak transaksi
            Total.setText(" Rp. " + TotalH); //menampilkan total bayar

            String nama,
                    kamar = "(" + Jumlahkamar.getValue() + ") " + Class.getSelectedItem(),
                    orang = Dewasa.getValue() + " Dewasa, " + Anak.getValue() + " Anak";
            if (Jeniskelamin.getSelectedItem().equals("Perempuan")) {
                nama = Nama.getText() + " (P)";
            } else {
                nama = Nama.getText() + " (L)";
            }

            tabel.addRow(new Object[]{nama, Alamat.getText(), nomertelp.getText(), Identitas.getSelectedItem(),
                kamar, orang, tgl1, tgl2, Total.getText()});

            String DataOrang = "Nama\t: " + Nama.getText()
                    + "\nAlamat\t: " + Alamat.getText()
                    + "\nNo. Telpon\t: " + nomertelp.getText()
                    + "\nJenis Kelamin\t: " + Jeniskelamin.getSelectedItem()
                    + "\nLama\t: " + TimeUnit.MILLISECONDS.toDays(jumlahhari) + " Hari";
            Datacustomer.setText(DataOrang);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terdapat Data yang belum terpilih");
            return;
        }
    }//GEN-LAST:event_ReservasiActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReservasiHotel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JSpinner Anak;
    private javax.swing.JButton Bersih;
    private javax.swing.JComboBox<String> Class;
    private javax.swing.JButton Close;
    private javax.swing.JTextArea Datacustomer;
    private com.toedter.calendar.JDateChooser Date1;
    private com.toedter.calendar.JDateChooser Date2;
    private javax.swing.JButton Delete;
    private javax.swing.JTextArea DetilKelas;
    private javax.swing.JSpinner Dewasa;
    private javax.swing.JComboBox<String> Identitas;
    private javax.swing.JComboBox<String> Jeniskelamin;
    private javax.swing.JLabel Jlabel;
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JLabel Jlabel2;
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JTextField Jumlah;
    private javax.swing.JSpinner Jumlahkamar;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Pajak;
    private javax.swing.JButton Reservasi;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField Total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomertelp;
    // End of variables declaration//GEN-END:variables
}
